/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_fizzylogic_reactivepi_spi_SPIDevice */

#ifndef _Included_nl_fizzylogic_reactivepi_spi_SPIDevice
#define _Included_nl_fizzylogic_reactivepi_spi_SPIDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_fizzylogic_reactivepi_spi_SPIDevice
 * Method:    initializeDevice
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_spi_SPIDevice_initializeDevice
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     nl_fizzylogic_reactivepi_spi_SPIDevice
 * Method:    transferData
 * Signature: (II[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_fizzylogic_reactivepi_spi_SPIDevice_transferData
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
