/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_fizzylogic_reactivepi_i2c_I2CDevice */

#ifndef _Included_nl_fizzylogic_reactivepi_i2c_I2CDevice
#define _Included_nl_fizzylogic_reactivepi_i2c_I2CDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    initializeDevice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_initializeDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    closeDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_closeDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    deviceWriteDirect
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_deviceWriteDirect
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    deviceWrite
 * Signature: (III[BII)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_deviceWrite
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    deviceReadDirect
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_deviceReadDirect
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     nl_fizzylogic_reactivepi_i2c_I2CDevice
 * Method:    deviceRead
 * Signature: (III[BII)I
 */
JNIEXPORT jint JNICALL Java_nl_fizzylogic_reactivepi_i2c_I2CDevice_deviceRead
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
